In [14]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

In [15]:
df = pd.read_csv(r"C:\Users\Asus\OneDrive\Desktop\birthday project\birthday_data.csv")

In [16]:
df.head()

   age likes_party favorite_activity favorite_color personality
0   18         yes            gaming          black   energetic
1   20          no           reading           blue        calm
2   19         yes            travel           pink      social
3   25          no            movies           gray   introvert
4   21         yes           dancing            red   energetic

In [ ]:
#label encoding
# convert to numbers for the model to understand
#0-->no
#1-->yes

le = LabelEncoder()

df["likes_party"] = le.fit_transform(df["likes_party"])
df["favorite_activity"] = le.fit_transform(df["favorite_activity"])
df["favorite_color"] = le.fit_transform(df["favorite_color"])
df["personality"] = le.fit_transform(df["personality"])

In [18]:
df.head()

   age  likes_party  favorite_activity  favorite_color  personality
0   18            1                  1               0            2
1   20            0                  5               1            0
2   19            1                  7               4            4
3   25            0                  2               2            3
4   21            1                  0               6            2

In [19]:
# feature and target

X = df.drop("personality", axis=1)
y = df["personality"]

In [20]:
# train model

model = DecisionTreeClassifier()
model.fit(X, y)

DecisionTreeClassifier()

In [21]:
# predication

prediction = model.predict([[20,1,3,2]])
print(prediction)

[1]

c:\Users\Asus\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:
# more simple way

new_data = pd.DataFrame(
    [[20,1,3,2]],
    columns=[
        "age",
        "likes_party",
        "favorite_activity",
        "favorite_color"
    ]
)

In [23]:
#test

prediction = model.predict(new_data)
print(prediction)

[1]

In [24]:
personality_names = {
    0: "calm",
    1: "creative",
    2: "energetic",
    3: "introvert",
    4: "social"
}

In [28]:
# test

print(personality_names[prediction[0]])

creative

In [49]:
print(
    "Summary:\n"
    "-This project predicts your personality:\n "
    "1-based on your age\n 2-favorite activity\n "
    "3-favorite color and whether you like parties or not.\n"
)


print(
    "Stemilt app:\n"
    "1-Enter your information and discover\n "
    "2-your birthday personality "
)

Summary:
-This project predicts your personality:
 1-based on your age
 2-favorite activity
 3-favorite color and whether you like parties or not.

Stemilt app:
1-Enter your information and discover
 2-your birthday personality